JMP MAIN
JMP isr
;KE SI NAPRAVESH DVA COUNTERA ZA KOLKU PATI DA GO IMASH NA SCREEN
;ILI MOZHESH PO LEVEL DA IMASH POVEKE AMA NEMASH POTREBA
;SEKOJ PAT TREBA EDENIO DA TI E BAREM ZA 1 POMALO
;KE GI STAVESH COUNTERITE TUKA PO SAFE E

;DA ZACHUVASH KOJ E POVEKE

;KE ZEMASH DATA SHO E PRETISNANO AKO E TOA PROVERI
;DALI E TOCHNO
;AKO NE NISHTO DA NE SE DESHAVA

;ARRAY TUKA

;OVAA E ZA SCREEN
QUIT: DW 0
COUNTER: DW 0x0039

isr:
PUSH A
MOV C, [COUNTER]

PRINT:
MOV A, 0
OUT 8
MOVB AH, CL
MOVB AL, 255
OUT 9
DEC C
MOV [COUNTER], C
CMP C, 0x002F
JNE TIMER

MOV [QUIT], 1

TIMER:
MOV A, 2
OUT 2
POP A
IRET

RANDOM_NUM:
IN 10
AND A, 0x0F1E
CMP A, 0x0004
JBE RANDOM_NUM
MOV D, A
;ARRAY DEKA SHO KE GI IMASH SITE POZICII ZA DA PROVERUVASH DA
;NE TI SE POFTORE NEKOJA
RET

MAIN:
;SP TI E ZA FUN
MOV SP, 0x0FFF
MOV A, 1
OUT 7
;SCREEN
MOV A, 1
OUT 7

MOV B, 20;COUNTER

;LISTO I BOJATA
MOVB CH, 6 ;OBJ
MOVB CL, 215; BOJA
;DRUGATA OPCIJA E DA IMASH ZA PRINT FUNKCIJA

;PRINTING ON SCREEN 20 LISTA
LEVEL:
DEC B; NAMALUVASH COUNTER
;CMP COUNTER 1 AKO NE SE SITE POVIKUVASH RNADOM NUM AKO
;NE PROVERI ZA COUNTER 2
CALL RANDOM_NUM
;CMP COUNTER 2 AKO NE SE POVUKUVASH RANDOM NUM AKO NE
;POCNUI OD POCHEKTOK
;POZICIJATA
MOV A, D
OUT 8
;OBJ
MOVB AH, CH
MOVB AL, CL
OUT 9
;COUNTER CHEK
CMP B, 0
JNE LEVEL
MOV A, 5000
OUT 3
MOV A, 2
OUT 0
STI
LOOP:
MOV A, [QUIT]
CMP A, 1
JE BREAK
JMP LOOP
BREAK:
CLI
MOV A, 3
OUT 7
HLT
;CLEAR SCREEN
;MOZHE DA GO ISKORISTESH ZA POSLE KOA PRVATA
;STRANA SHO E START GAME
;MOV A, 3
;OUT 7
; KE TREBA DA NAPVAESH I END SCREEN ZA WIN I ZA GAME OVER
; I KE STAVESH KAJ KEYBOARD DA TI NAPISHE PRESS R FOR RESTART
